version: "3.3"
services:
  proxy:
    build: './nginx'
    container_name: proxy
    restart: always
    environment: 
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WWW_DOMAIN_NAME=${WWW_DOMAIN_NAME}
      - DOMAIN_IP=${DOMAIN_IP}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL}
    networks: 
      - frontend
    depends_on:
      - apache
    ports:
      # Solo el proxy tiene puertos expuestos,
      # los demas contenedores salen por aqui.
      - "80:80"
      - "443:443"
  php:
    build: './php/'
    container_name: php
    restart: always
    networks:
      - backend
    volumes:
      #CUSTOM rename with YOUR_APP_VOLUME_NAME
      - APP_VOLUME:/var/www/html/
  apache:
    build: './apache/'
    container_name: server
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - mysql
    volumes:
      #CUSTOM rename with YOUR_APP_VOLUME_NAME
      - APP_VOLUME:/var/www/html/
  mysql:
    image: mysql:5.6.40
    container_name: db
    restart: always
    #CUSTOM remove ports if you dont want to access DBMS from host 
    ports: 
      - "127.0.0.1:3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
      #CUSTOM rename with YOUR_DB_VOLUME_NAME
      - DB_VOLUME:/var/lib/mysql/
volumes:
  # CUSTOM
  APP_VOLUME:
  DB_VOLUME:
networks:
  frontend:
  backend: