version: "0.0"
services:
  php:
    build: './php/'
    restart: always
    networks:
      - backend
    volumes:
      - /var/www/html/:/var/www/html/
  apache:
    build: './apache/'
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - /var/www/html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    restart: always
    ports: [3306:3306]
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=1234
networks:
  frontend:
  backend: